export const START_CREATE_BUDGET = 'START_CREATE_BUDGET';
export const ADD_BUDGET_SUCCESS = 'ADD_BUDGET_SUCCESS';
export const START_EDIT_BUDGET = 'START_EDIT_BUDGET';
export const EDIT_BUDGET_SUCCESS = 'EDIT_BUDGET_SUCCESS';
export const SET_BUDGET = 'SET_BUDGET'
export const LOGOUT_BUDGET = 'LOGOUT_BUDGET'

// export const START_CREATE_BUDGET = 'START_CREATE_BUDGET';
// export const START_CREATE_BUDGET = 'START_CREATE_BUDGET';
// export const START_CREATE_BUDGET = 'START_CREATE_BUDGET';
// export const START_CREATE_BUDGET = 'START_CREATE_BUDGET';