export const START_CREATE_BUDGET = 'START_CREATE_BUDGET';
export const ADD_BUDGET_SUCCESS = 'ADD_BUDGET_SUCCESS';
export const START_EDIT_BUDGET = 'START_EDIT_BUDGET';
export const EDIT_BUDGET_SUCCESS = 'EDIT_BUDGET_SUCCESS';
export const SET_BUDGET = 'SET_BUDGET'
export const LOGOUT_BUDGET = 'LOGOUT_BUDGET'

export const START_ADD_SAVING = 'START_ADD_SAVING'
export const ADD_SAVING_SUCCESS = 'ADD_SAVING_SUCCESS'
export const START_UPDATE_SAVING = 'START_UPDATE_SAVING' 
export const UPDATE_SAVING_SUCCESS = 'UPDATE_SAVING_SUCCESS'  
export const SET_SAVINGS = 'SET_SAVINGS'
export const LOGOUT_SAVINGS = 'LOGOUT_SAVINGS'

export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS'
export const EDIT_TRANSACTION_SUCCESS = 'EDIT_TRANSACTION_SUCCESS'
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS'
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS'
export const LOGOUT_TRANSACTIONS = 'LOGOUT_TRANSACTIONS'


