export default {
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_SIZE_HEADER: 50,
  STANDARD_SPACING: 25,
  PRIMARY_COLOR: '#f5f9ff',
  SECONDARY_COLOR: '#00b5ec',
  ACCENT_COLOR: 'blue',

  FORM_WIDTH: 300
};